POST http://localhost:5000/api/posts/61318ad1d49397494021db82/comment
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTMxOGE5YTExNjMwZjQ3ZTRjODg4N2YiLCJpYXQiOjE2MzA2NjAzOTh9.VAvznl_wp_7lQzcB_UOxgmzwvcegQr5oGOVVg2Www2I

{
    "content":"this is comment"
}
